/********************************************************************
* psbDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error psbDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablepsbDict();
extern void G__cpp_setup_inheritancepsbDict();
extern void G__cpp_setup_typetablepsbDict();
extern void G__cpp_setup_memvarpsbDict();
extern void G__cpp_setup_globalpsbDict();
extern void G__cpp_setup_memfuncpsbDict();
extern void G__cpp_setup_funcpsbDict();
extern void G__set_cpp_environmentpsbDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "psb.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__psbDictLN_TClass;
extern G__linked_taginfo G__psbDictLN_TBuffer;
extern G__linked_taginfo G__psbDictLN_TMemberInspector;
extern G__linked_taginfo G__psbDictLN_TObject;
extern G__linked_taginfo G__psbDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__psbDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__psbDictLN_TClonesArray;
extern G__linked_taginfo G__psbDictLN_TGObject;
extern G__linked_taginfo G__psbDictLN_TQObject;
extern G__linked_taginfo G__psbDictLN_TGWindow;
extern G__linked_taginfo G__psbDictLN_TGFrame;
extern G__linked_taginfo G__psbDictLN_TGCompositeFrame;
extern G__linked_taginfo G__psbDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__psbDictLN_TGTextButton;
extern G__linked_taginfo G__psbDictLN_TGVerticalFrame;
extern G__linked_taginfo G__psbDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__psbDictLN_TGMainFrame;
extern G__linked_taginfo G__psbDictLN_TGPopupMenu;
extern G__linked_taginfo G__psbDictLN_TGDockableFrame;
extern G__linked_taginfo G__psbDictLN_TGTab;
extern G__linked_taginfo G__psbDictLN_TGStatusBar;
extern G__linked_taginfo G__psbDictLN_TGMenuBar;
extern G__linked_taginfo G__psbDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__psbDictLN_TGNumberEntry;
extern G__linked_taginfo G__psbDictLN_TGLabel;
extern G__linked_taginfo G__psbDictLN_TGListBox;
extern G__linked_taginfo G__psbDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__psbDictLN_TChain;
extern G__linked_taginfo G__psbDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__psbDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__psbDictLN_PSbMainFrame;
extern G__linked_taginfo G__psbDictLN_maplEunsignedsPintcOTH1DmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTH1DmUgRsPgRsPgR;
extern G__linked_taginfo G__psbDictLN_maplEintcOmaplEunsignedsPintcOTH1DmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTH1DmUgRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOmaplEunsignedsPintcOTH1DmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOTH1DmUgRsPgRsPgRsPgRsPgRsPgR;

/* STUB derived class for protected member access */
